# ===================================================
# Server
# ===================================================
server.port=8761
spring.application.name=discovery-server

# ===================================================
# Eureka Server
# ===================================================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0

# ===================================================
# Disable DataSource AutoConfiguration
# Discovery service uses raw JDBC only for DB init
# ===================================================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ===================================================
# DB Superuser ? initial DB + user creation only
# ===================================================
db.superuser.url=jdbc:postgresql://localhost:5432/postgres
db.superuser.username=postgres
db.superuser.password=admin

# ===================================================
# App DB ? what to create
# ===================================================
db.app.name=fund-transfer
db.app.username=fund-transfer
db.app.password=fund-transfer

# ===================================================
# Logging
# ===================================================
logging.level.com.fund.transfer.discovery=DEBUG